stages:
  - build
  - push

build_docker_image:
  stage: build
  only:
    - main
  script:
    - echo "start docker image"
    - /usr/bin/docker build -t ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_IID} -t ${CI_REGISTRY_IMAGE}:latest .

push_docker_image:
  stage: push
  only:
    - main
  script:
    - echo "start push docker image"
    - /usr/bin/docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - /usr/bin/docker push ${CI_REGISTRY_IMAGE}:latest
